sudo: false
before_install:
  - script/vendor-deb libicu48 libicu-dev
  - bundle config build.charlock_holmes --with-icu-include=$(pwd)/vendor/debs/include --with-icu-lib=$(pwd)/vendor/debs/lib
install: bundle install --jobs=3 || find . -name mkmf.log -exec cat {} \;
script:
  - git fetch origin master:master
  - git fetch origin v2.0.0:v2.0.0
  - git fetch origin test/attributes:test/attributes
  - git fetch origin test/master:test/master
  - git submodule init
  - git submodule sync --quiet
  - script/fast-submodule-update
  - bundle exec rake
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
notifications:
  disabled: true
git:
  submodules: false
cache: bundler
